codecov:
  require_ci_to_pass: true

coverage:
  range: "60...100"  # Rango más amplio para aprendizaje
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70%  # Objetivo accesible para el proyecto completo
        threshold: 5%  # Umbral más permisivo
        if_not_found: success
    patch:
      default:
        target: 60%  # Muy permisivo para cambios
        threshold: 10%  # Gran margen para experimentar
    changes:
      default:
        target: 70%  # Objetivo razonable para código nuevo
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no  # Mantiene comentarios para aprendizaje
  branches: false

flags:
  flutter:
    paths:
      - lib/
    carryforward: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.gr.dart"
  - "test/**"
