codecov:
  require_ci_to_pass: true

coverage:
  range: "60...100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
  branches: ["main", "dev"]

flags:
  logic:
    paths:
      - lib/auth/
      - lib/models/
      - lib/providers/
      - lib/services/
    carryforward: true
  ui:
    paths:
      - lib/pages/
      - lib/widgets/
    carryforward: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.gr.dart"
  - "test/**"
