codecov:
  require_ci_to_pass: true

coverage:
  range: "60...100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
  branches: ["main", "dev"]

flags:
  flutter:
    paths:
      - lib/
    carryforward: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.gr.dart"
  - "test/**"
