version: 2
updates:
  # Mantener dependencias para pub (Flutter/Dart)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "Elebrimir"
      - "pablo-cort-s73"
    labels:
      - "dependencies"
      - "dart"

  # Mantener dependencias para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
