repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc

  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart
        args: ["format", "."]
        language: system
        pass_filenames: false

      - id: flutter-analyze
        name: flutter analyze
        entry: flutter
        args: ["analyze"]
        language: system
        pass_filenames: false
