// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlUDrBpc2Sni7PrpShx6oCbTLsb9WWnME',
    appId: '1:313522586898:web:8bec61d6071eef19479fcb',
    messagingSenderId: '313522586898',
    projectId: 'hccapp-1de7c',
    authDomain: 'hccapp-1de7c.firebaseapp.com',
    storageBucket: 'hccapp-1de7c.firebasestorage.app',
    measurementId: 'G-QRRNQLQ5NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJp7r10jM6J14lIUzpuHpuyUzzpHEoUw',
    appId: '1:313522586898:android:3dd557c94cf15e36479fcb',
    messagingSenderId: '313522586898',
    projectId: 'hccapp-1de7c',
    storageBucket: 'hccapp-1de7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAj0dtOHmz-ToV67GmiNOAl8UK4zbTfQ',
    appId: '1:313522586898:ios:6386852e70cc7f3a479fcb',
    messagingSenderId: '313522586898',
    projectId: 'hccapp-1de7c',
    storageBucket: 'hccapp-1de7c.firebasestorage.app',
    iosBundleId: 'com.example.hccApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdAj0dtOHmz-ToV67GmiNOAl8UK4zbTfQ',
    appId: '1:313522586898:ios:6386852e70cc7f3a479fcb',
    messagingSenderId: '313522586898',
    projectId: 'hccapp-1de7c',
    storageBucket: 'hccapp-1de7c.firebasestorage.app',
    iosBundleId: 'com.example.hccApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlUDrBpc2Sni7PrpShx6oCbTLsb9WWnME',
    appId: '1:313522586898:web:5d7d3cb61c1f7640479fcb',
    messagingSenderId: '313522586898',
    projectId: 'hccapp-1de7c',
    authDomain: 'hccapp-1de7c.firebaseapp.com',
    storageBucket: 'hccapp-1de7c.firebasestorage.app',
    measurementId: 'G-EXRPLJ6LCL',
  );
}
